### ISSUE TITLE
[Bug] BetterDiscord instability & crashes when viewing certain text formats

### ISSUE THREAD

**Issue by QuentinMcCarthy** [BetterDiscord/BetterDiscord#1222]
**Describe the Bug**
Certain text formats (such as the box embeds bots can post) will crash BD. Given Discord opens to those channels after a reload, this crash is permanent until Discord is either fully closed down, or BD is reinstalled; opening the friends list by default. Since the fix for the latest Discord update, this version of BD is rather unstable in general (lots of plugin errors as well)

**To Reproduce**
Attempt to view a channel containing the bot embed box (such as the #github-log channel in the BD Discord) or similar formatting options.

**Expected Behavior**
Channel loads and displays as normal

**Screenshots**

**Discord Version**
Stable

**Additional Context**

**Comment by rauenzi** [comment]
Does the crashing occur without any plugins installed? Plugins often need to make their own changes separate from BD when Discord updates.

**Comment by K4zoku** [comment]
> Does the crashing occur without any plugins installed? Plugins often need to make their own changes separate from BD when Discord updates.

it worked without any plugins, I am testing each plugin to find out which plugin cause the crash

**Comment by TrueMLGPro** [comment]
This crash just occured for me as well
Here's what the console prints out:
```log
Prettified stacktraces, stack:
 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 
Component stack:
     at span
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1650:73
    at span
    at h2
    at https://discord.com/assets/fb1f1576ed1d453163fe.js:1059:319
    at div
    at div
    at t.default (https://discord.com/assets/288bc8ed74323c900218.js:1953:172)
    at li
    at t.default (https://discord.com/assets/288bc8ed74323c900218.js:1953:172)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1650:73
    at ol
    at div
    at p (https://discord.com/assets/288bc8ed74323c900218.js:1962:545)
    at div
    at https://discord.com/assets/fb1f1576ed1d453163fe.js:1514:872
    at div
    at E (https://discord.com/assets/288bc8ed74323c900218.js:3550:180)
    at H (https://discord.com/assets/fb1f1576ed1d453163fe.js:1011:489)
    at https://discord.com/assets/fb1f1576ed1d453163fe.js:1014:611
    at main
    at Te (https://discord.com/assets/40013fde4987fc0228da.js:74:819)
    at https://discord.com/assets/fb1f1576ed1d453163fe.js:1524:878
    at t (https://discord.com/assets/288bc8ed74323c900218.js:3202:414)
    at ChatLayerProvider
    at t (https://discord.com/assets/f89a1b32de3f9305fc8f.js:23:104)
    at t (https://discord.com/assets/40013fde4987fc0228da.js:82:452)
    at https://discord.com/assets/40013fde4987fc0228da.js:87:623
    at div
    at div
    at t (https://discord.com/assets/40013fde4987fc0228da.js:53:923)
    at e (https://discord.com/assets/2e45b6b321248222f12a.js:44:760)
    at https://discord.com/assets/f89a1b32de3f9305fc8f.js:57:342
    at https://discord.com/assets/40013fde4987fc0228da.js:67:386
    at re (https://discord.com/assets/40013fde4987fc0228da.js:35:591)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5505:926)
    at c (https://discord.com/assets/288bc8ed74323c900218.js:1806:291)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5508:10)
    at div
    at div
    at div
    at Me (https://discord.com/assets/40013fde4987fc0228da.js:39:31)
    at div
    at l (https://discord.com/assets/288bc8ed74323c900218.js:4116:605)
    at t (https://discord.com/assets/40013fde4987fc0228da.js:135:344)
    at div
    at t (https://discord.com/assets/288bc8ed74323c900218.js:4025:281)
    at t (https://discord.com/assets/40013fde4987fc0228da.js:137:946)
    at K (https://discord.com/assets/40013fde4987fc0228da.js:139:509)
    at div
    at t (https://discord.com/assets/5c091cbf84346774e26c.js:5:674)
    at k (https://discord.com/assets/40013fde4987fc0228da.js:116:188)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5505:926)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5508:10)
    at t (https://discord.com/assets/40013fde4987fc0228da.js:214:85)
    at u (https://discord.com/assets/288bc8ed74323c900218.js:3710:833)
    at Suspense
    at d
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5505:926)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5508:10)
    at div
    at y (https://discord.com/assets/288bc8ed74323c900218.js:3235:435)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:3202:414)
    at VerificationLayerProvider
    at t (https://discord.com/assets/288bc8ed74323c900218.js:3202:414)
    at AppLayerProvider
    at p (https://discord.com/assets/288bc8ed74323c900218.js:1962:545)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:705:521)
    at T (https://discord.com/assets/288bc8ed74323c900218.js:707:975)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:708:442)
    at u (https://discord.com/assets/288bc8ed74323c900218.js:3710:833)
    at h (https://discord.com/assets/288bc8ed74323c900218.js:692:9)
    at te (https://discord.com/assets/288bc8ed74323c900218.js:695:605)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:751:24)
    at u (https://discord.com/assets/288bc8ed74323c900218.js:3709:772)
    at https://discord.com/assets/288bc8ed74323c900218.js:4180:30
    at H (https://discord.com/assets/288bc8ed74323c900218.js:5319:700)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5502:570)
    at t (https://discord.com/assets/288bc8ed74323c900218.js:5458:817)
    at f (https://discord.com/assets/288bc8ed74323c900218.js:2227:987)
 ```
 
 It looks like there's some problem with ZeresPluginLibrary

**Comment by K4zoku** [comment]
> I'm getting this issue and from the process of elimination, it looks like "BetterBotTags.plugin.js" is causing a crash when viewing a channel with lots of bot posts.
> 
> Got this in console
> 
> ![image](https://user-images.githubusercontent.com/6209681/154260833-0ce2340f-71b9-402f-ac8a-9c4afde3fb42.png)

delete BetterBotTags.plugin.js and BD worked well

**Comment by MrJDucky** [comment]
> > I'm getting this issue and from the process of elimination, it looks like "BetterBotTags.plugin.js" is causing a crash when viewing a channel with lots of bot posts.
> > Got this in console
> > ![image](https://user-images.githubusercontent.com/6209681/154260833-0ce2340f-71b9-402f-ac8a-9c4afde3fb42.png)
> 
> delete BetterBotTags.plugin.js and BD worked well

Can confirm by removing BetterBotTags, BD works fully as intended so far.
