### ISSUE TITLE
Unable to reinstall BetterDiscord Discord won't open

### ISSUE THREAD

**Issue by gobrienstrath** [BetterDiscord/BetterDiscord#1375]
**Describe the Bug**
After updating had to reinstall better discord the automatic install method does not work, tried to clone the repo and install with npm which has worked in the past. npm build fails, and now discord won't even open because it's looking for BetterDiscord/dist files, which don't exist

**To Reproduce**
reinstall better discord

**Expected Behavior**
clean install

**Screenshots**
![image](https://user-images.githubusercontent.com/97900522/185712285-08c1325c-dba0-4c37-b74c-d73309bfe927.png)
![image](https://user-images.githubusercontent.com/97900522/185712410-78537021-e06f-4c91-9058-cd62679a761f.png)

**Discord Version**
stable

**Additional Context**
terminal output: 
```
> betterdiscord@1.6.3 build
> npm run build-injector && npm run build-renderer


> betterdiscord@1.6.3 build-injector
> npm run build --prefix injector


> betterdiscord-injector@0.6.2 build
> webpack --progress --color

10% building 0/1 entries 0/0 dependencies 0/0 modulesnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/gergo/BetterDiscord/injector/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/home/gergo/BetterDiscord/injector/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/home/gergo/BetterDiscord/injector/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/home/gergo/BetterDiscord/injector/node_modules/webpack/lib/NormalModule.js:753:17)
    at handleParseResult (/home/gergo/BetterDiscord/injector/node_modules/webpack/lib/NormalModule.js:817:10)
    at /home/gergo/BetterDiscord/injector/node_modules/webpack/lib/NormalModule.js:908:4
    at processResult (/home/gergo/BetterDiscord/injector/node_modules/webpack/lib/NormalModule.js:640:11)
    at /home/gergo/BetterDiscord/injector/node_modules/webpack/lib/NormalModule.js:692:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
} ```

**Comment by SmolAlli** [comment]
The error comes from you using the latest version of Node, you need to be using the LTS version (16).
