### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Gabetoo** [BetterDiscord/BetterDiscord#1380]
**Describe the Bug**
If I send a messagge when im in call, it disconnects. Im not sure if the problem is some plugin or Better Discord

**To Reproduce**
Send a messagge in VC.

**Expected Behavior**
Idk, chat like usual?

**Screenshots**
![image](https://user-images.githubusercontent.com/100107012/186304895-f5a6cd95-1a8e-49b7-8abf-47f9662e382d.png)
Could this mean anything? I didn't know what to search and the only thing that seamed weird was this. Maybe is nothing but just in case.

**Comment by maenDisease** [comment]
This is not a BetterDiscord issue, this is an issue with one of your plugins.

**Comment by Gabetoo** [comment]
> This is not a BetterDiscord issue, this is an issue with one of your plugins.

Oh, okay. Thanks!

**Comment by Gabetoo** [comment]
> This is not a BetterDiscord issue, this is an issue with one of your plugins.

Sorry, me again. Is there any place to ask for this kind of issues? Or at least can you give me an advice for knowing what im searching of?

**Comment by mahnyu** [comment]
Have you found which plugin causes this behavior?

**Comment by maenDisease** [comment]
You can ask in the BetterDiscord support server to troubleshoot your issue. The Invite is the second button in https://betterdiscord.app

**Comment by Gabetoo** [comment]
> Have you found which plugin causes this behavior?

Nope, only this but probably doesn't mean anything: 
[2022-08-23 22:00:21.295][CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. m => "ActivityStatus" === m.default.displayName Cannot read property 'displayName' of undefined
TypeError: Cannot read property 'displayName' of undefined
    at eval (betterdiscord://plugins/ActivityIcons.plugin.js:96:111)
    at s (<anonymous>:4:57078)
    at Function.getModule (<anonymous>:4:57429)
    at Object.B.findModule (<anonymous>:4:330085)
    at ActivityIcons.onStart (betterdiscord://plugins/ActivityIcons.plugin.js:96:64)
    at ActivityIcons.start (betterdiscord://plugins/0PluginLibrary.plugin.js:3917:58)
    at Object.startPlugin (<anonymous>:4:43560)
    at Object.startAddon (<anonymous>:4:43353)
    at Object.loadAddon (<anonymous>:4:9229)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.loadAllAddons (<anonymous>:4:11269)
    at Object.initialize (<anonymous>:4:5963)
    at Object.initialize (<anonymous>:4:40050)
    at Object.startup (<anonymous>:4:374950)
    
    
    [2022-08-23 22:00:24.200][CONSOLE:WARN] [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. m => m?.default.displayName === "RoleMention" Cannot read property 'displayName' of undefined
TypeError: Cannot read property 'displayName' of undefined
    at eval (betterdiscord://plugins/RoleMentionIcons.plugin.js:81:65)
    at s (<anonymous>:4:57078)
    at Function.getModule (<anonymous>:4:57429)
    at Object.B.findModule (<anonymous>:4:330085)
    at plugin (betterdiscord://plugins/RoleMentionIcons.plugin.js:81:39)
    at eval (betterdiscord://plugins/RoleMentionIcons.plugin.js:137:16)
    at eval (betterdiscord://plugins/RoleMentionIcons.plugin.js:138:7)
    at eval (betterdiscord://plugins/RoleMentionIcons.plugin.js:139:3)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.loadAllAddons (<anonymous>:4:11269)
    at Object.initialize (<anonymous>:4:5963)
    at Object.initialize (<anonymous>:4:40050)
    at Object.startup (<anonymous>:4:374950)

**Comment by Wilczev** [comment]
It's messageloggerv2 causing this (atleast for me). I don't know how to fix this.

**Comment by Gabetoo** [comment]
> It's messageloggerv2 causing this (atleast for me). I don't know how to fix this.

Yeah probably. I opened Discord today and appeared this:
![image](https://user-images.githubusercontent.com/100107012/186513925-eb64b5d9-5b26-4397-8f73-d04fa3227b7b.png)
Error: ENOENT: no such file or directory, open 'C:\Users\gabriel\AppData\Roaming\BetterDiscord\plugins\MessageLoggerV2'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
No idea how to solve.

**Comment by Gabetoo** [comment]
> > It's messageloggerv2 causing this (atleast for me). I don't know how to fix this.
> 
> Yeah probably. I opened Discord today and appeared this: ![image](https://user-images.githubusercontent.com/100107012/186513925-eb64b5d9-5b26-4397-8f73-d04fa3227b7b.png) Error: ENOENT: no such file or directory, open 'C:\Users\gabriel\AppData\Roaming\BetterDiscord\plugins\MessageLoggerV2' at Object.openSync (fs.js:476:3) at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846) at Object.readFileSync (fs.js:377:35) at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872) No idea how to solve.

![image](https://user-images.githubusercontent.com/100107012/186514817-96be165f-7b2a-4e48-9121-6f1424cc3785.png)
lol
