### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LuluTheCatgirl** [BetterDiscord/BetterDiscord#1548]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

betterdiscord keeps crashing everytime i try to select the settings icon 

### Expected Behavior

unless the developers find a way to make this bug go away i expect this to happen everytime i try to go to my discord settings

### Steps To Reproduce

latest version of better discord
no theme
klick settings
will probably crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

latest

**Comment by almightyyoda2012** [comment]
Same issue, I've attached a screenshot of the console log error:

![image](https://user-images.githubusercontent.com/4081079/221933954-8f71760f-8885-40d6-85ae-181b6e506a6e.png)

Error Text:
```
Uncaught Error: Assignment to constant variable.
    at IncomingMessage.<anonymous> (C:\Users\almig\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\preload.js:1:3740)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ff334c0250254fc1c9ca.js:152 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at wc (288aa17d3bf2f0a3351d.js:1667)
    at d (288aa17d3bf2f0a3351d.js:1602)
    at E (288aa17d3bf2f0a3351d.js:1604)
    at e (288aa17d3bf2f0a3351d.js:1606)
    at vs (288aa17d3bf2f0a3351d.js:1618)
    at yu (288aa17d3bf2f0a3351d.js:1663)
    at Oc (288aa17d3bf2f0a3351d.js:1655)
    at Ic (288aa17d3bf2f0a3351d.js:1655)
    at hc (288aa17d3bf2f0a3351d.js:1654)
    at ic (288aa17d3bf2f0a3351d.js:1651)
    at oc (288aa17d3bf2f0a3351d.js:1650)
    at g (288aa17d3bf2f0a3351d.js:1772)
    at L (288aa17d3bf2f0a3351d.js:1773)
    at t.exports (ff334c0250254fc1c9ca.js:21)
    at g.<computed> (ff334c0250254fc1c9ca.js:36)
    at Number.m (ff334c0250254fc1c9ca.js:36)
    at MessagePort.b (ff334c0250254fc1c9ca.js:36)
(anonymous) @ ff334c0250254fc1c9ca.js:152
```

**Comment by almightyyoda2012** [comment]
same as https://github.com/BetterDiscord/BetterDiscord/issues/1540

**Comment by Matt0040** [comment]
Not sure if they're connected but the installer fails atm too so DO NOT UNINSTALL. You get this: 
![image](https://user-images.githubusercontent.com/42654785/221936665-14f53ae8-2458-46cc-96f6-ef5358458fd9.png)

Which links here: https://api.github.com/repos/BetterDiscord/BetterDiscord/releases

**Comment by Ping777777** [comment]
As of today I have experienced the same issue.

**Comment by lukas5450** [comment]
same

**Comment by rauenzi** [comment]
This has been fixed in the latest release
