### ISSUE TITLE
[Bug] TypeError: e.systemPreferences.getAccentColor is not a function

### ISSUE THREAD

**Issue by guihkx** [BetterDiscord/BetterDiscord#1737]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

I get this error at Discord startup:

```js
Error occurred in handler for 'bd-get-accent-color': TypeError: e.systemPreferences.getAccentColor is not a function
    at D (/home/gui/.var/app/com.discordapp.Discord/config/BetterDiscord/data/betterdiscord.asar/injector.js:1:6662)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77979)
    at WebContents.emit (node:events:517:28)
    at WebContents.emit (node:domain:489:12)
    at emitter.emit (/app/discord/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:116:20)
```

### Expected Behavior

No error.

### Steps To Reproduce

1. Launch Discord on Linux

### Operating System

Linux

### Discord Version

Stable

### BetterDiscord Version

1.10.1

### Anything else?

```md
## Discord Info
stable 282068 (6e25b1c) Host 0.0.47 x64 Linux 64-bit (6.8.4-arch1-1)

## BetterDiscord
stable 1.10.1

### Themes (1 Enabled):
- AMOLED-Cord (Enabled)
```

**Comment by zerebos** [comment]
Are you still experiencing this on the latest version?

**Comment by guihkx** [comment]
Sorry, I'm not using BetterDiscord anymore so I won't be able to verify that, so feel free to close this one.
