### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by aewastaken** [BetterDiscord/BetterDiscord#829]
**Describe the Bug**

*Better Discord crashes Discord client*

**To Reproduce**

*click on **any** chat*

**Expected Behavior**

*show chat*

**Screenshots**

https://user-images.githubusercontent.com/80064625/121227461-e00eae80-c88b-11eb-96b9-766a3a0e0cac.mov
*and window message*
![Zrzut ekranu 2021-06-8 o 7 00 10 PM](https://user-images.githubusercontent.com/80064625/121227511-f157bb00-c88b-11eb-929c-4ee0a6e64f4e.png)

**Discord Version**

*Stable 86917 (ace8ac3)*
*Host 0.0.263*
*OS X 11.0.0 (20.4.0)*

**Additional Context**

*reinstal or repair didnt worked at all.*

**Comment by rauenzi** [comment]
Is anyone else having this issue?

**Comment by Technetium1** [comment]
@rauenzi Yes, on Windows 10 and Arch.

**Comment by Lubieerror** [comment]
Yes. Me and my friend.
Both of us on W10 (me pro, x64, him idk). The worst part is that it seems to be unrelated to anything we're doing.
Playing games and talking, talking and writing, just clicking stuff (above). It always happened in late hours (23:00-02:00 UTC+2 time).

Starting Debug Log (2021-07-04 20:55:49.863) 
Since log (for me) is UTC+0, the correct time is +2h = 22:55:49.863. I manually corrected all other times here.

2h later: We were talking and our clients crashes synchronously at about 00:57:47.644 (estimated from last log message), then like 30 min later, little before 01:34:58.457 it happened again [to both of us] (estimated from next log start). 
**This one was without plugins as crash disabled them all (bttv settings was not shown, logs are empty).** (injector fault? something else was loaded? Discord fault but "bttv crash window" (this one above) was injected?)
I manually quit discord through tray icon and restarted it to get my plugins and themes back (also to remember crash moment in logs). It happened again twice to him but not to me (estimated time between crashes: again <30 min).

The most frequent message (29 at that moment, few in the row 7 times) from debug.log was:

```log
[2021-07-04 21:59:54.634][CONSOLE:DEBUG] Suppressed error in qReact query:
 {} Cannot read property 'maxValue' of undefined
TypeError: Cannot read property 'maxValue' of undefined
    at <anonymous>:118:71
    at qReact (<anonymous>:41:17)
    at qReact (<anonymous>:50:28)
    at qReact (<anonymous>:50:28)
    at qReact (<anonymous>:50:28)
    at after (<anonymous>:118:36)
    at Object.callback (<anonymous>:4:245480)
    at MenuControlItem (<anonymous>:4:155228)
    at _a (https://discord.com/assets/a9a865842245be0e7de5.js:2:3994885)
    at Ja (https://discord.com/assets/a9a865842245be0e7de5.js:2:4003248)
    at Ls (https://discord.com/assets/a9a865842245be0e7de5.js:2:4043808)
    at yu (https://discord.com/assets/a9a865842245be0e7de5.js:2:4027706)
    at Iu (https://discord.com/assets/a9a865842245be0e7de5.js:2:4027631)
    at lu (https://discord.com/assets/a9a865842245be0e7de5.js:2:4024558)
    at https://discord.com/assets/a9a865842245be0e7de5.js:2:3981290
    at t.unstable_runWithPriority (https://discord.com/assets/a9a865842245be0e7de5.js:2:4059297)
    at zi (https://discord.com/assets/a9a865842245be0e7de5.js:2:3980999)
    at Qi (https://discord.com/assets/a9a865842245be0e7de5.js:2:3981235)
    at Ji (https://discord.com/assets/a9a865842245be0e7de5.js:2:3981170)
    at fu (https://discord.com/assets/a9a865842245be0e7de5.js:2:4025075)
    at Ln (https://discord.com/assets/a9a865842245be0e7de5.js:2:3964617)
    at HTMLDocument.r (https://discord.com/assets/57c4676fe004fd600130.js:2:127584)
    at HTMLDivElement.r (https://discord.com/assets/a9a865842245be0e7de5.js:2:1347093)
    at HTMLDivElement.r (https://discord.com/assets/57c4676fe004fd600130.js:2:127584)
    ```
    
    But last one was at 23:59:54.634 so hour before crash.
    Last one was:
    `[2021-07-04 22:57:47.644][CONSOLE:INFO] [Connection] Creating user: XXXXXXXXXXXXXXXXXX with audio SSRC: XXXXXX and video SSRC: 0`
    Seems unrelated and also happens frequently.

**Comment by Lubieerror** [comment]
Since last update the problem disappeared for me.
